import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar/Navbar'
import Footer from './components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='sticky top-0 right-0 left-0'>
            <Navbar/>
        </header>
        {children}
        <footer>
            <Footer/>
        </footer>
      
      </body>
    </html>
  )
}

